### ISSUE TITLE
关于购买的疑问

### ISSUE THREAD

**Issue by t3hp0rP** [CyberPeace/ciscn2018-template#2]
原始模版购买的时候只按照price, 这样的话货物总量无法购买后-1
checker里面也是只传一个price, 修复购买-1之后无法通过checker

**Comment by kingkaki** [comment]
+1，也想问这个

**Comment by sco4x0** [comment]
@Pr0phet @kingkaki 模板程序只实现最基本的功能，我理解的商品购买中，更重要的是用户金额在购买成功后会发生变化，所以只实现了用户金额的减少与检查。选手的话是需要将这种存在缺陷的地方根据自己的理解和需求去进行功能完善的。可能readme中没说清楚，抱歉

**Comment by t3hp0rP** [comment]
请问checker是不会再改变了是吗?

**Comment by sco4x0** [comment]
@Pr0phet checker的话基本上不会再有修改了，如果程序，checker因为什么问题有所改动的话，一般会在群里发公告的

**Comment by t3hp0rP** [comment]
好的Orz 感谢大佬抽空解惑

**Comment by kingkaki** [comment]
checker.py不变的话，那只post一个price参数，似乎确定不了对应的物品，也就无法将数量减一。
是否意味着可以对这方面没有过强的限制要求（由于再readme中看到 `业务逻辑上设计防止“薅羊毛”的特性`  这句话）

**Comment by kingkaki** [comment]
@sco4x0 能帮忙解答一下上面的问题么

**Comment by sco4x0** [comment]
@kingkaki 关于这个问题在题目readme中有提到，[web程序说明](https://github.com/CyberPeace/ciscn2018-template/tree/master/CISCN-2018-web-for-players#web%E7%A8%8B%E5%BA%8F%E8%AF%B4%E6%98%8E)，因为模板程序只实现基本功能，所以checker中的参数应该是不定的，也就是说你可以根据自己的功能要求额外扩展参数，但是不允许减少和修改基本流程，这些改动应该在 `template/README.md` 文件中提及

**Comment by t3hp0rP** [comment]
如果我没有理解错的话...我们应该是可以自己修改并增加checker中的参数的?(只要不减少和修改基本流程)

**Comment by sco4x0** [comment]
@Pr0phet readme里写了的啊。 `各个请求参数应遵循checker脚本中所提交的参数，可以进行功能与参数扩展，不允许删减功能与参数`
